api/urls.py
"""
Propietario: grIT
Contacto: agustin.gomez.mansilla@gmail.com

Use of this code for any commercial purpose is NOT AUTHORIZED.
El uso de éste código para cualquier propósito comercial NO ESTÁ AUTORIZADO.
"""

from django.urls import path
from .views import *
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('search/persona/', Personas.as_view()),
    path('evento/getlistas/', get_listas_for_persona_and_evento)
]

conf/urls.py
"""
Propietario: grIT
Contacto: agustin.gomez.mansilla@gmail.com

Use of this code for any commercial purpose is NOT AUTHORIZED.
El uso de éste código para cualquier propósito comercial NO ESTÁ AUTORIZADO.
"""

from django.contrib import admin
from django.urls import path, include, reverse
from django.contrib.sitemaps import Sitemap
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView
from eventos.views import LoginView
from eventos.forms import UserLoginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'accounts/login/',
        LoginView.as_view(
            template_name="registration/login.html",
            form_class=UserLoginForm
            ),
        name='login'
    ),
    path("accounts/", include("django.contrib.auth.urls")),
    path('', include('eventos.urls')),
    path('api/', include('api.urls')),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path('csp/', include('cspreports.urls')),
    path("pricing", TemplateView.as_view(template_name="pricing.html"))
]


class StaticViewSitemap(Sitemap):
    priority = 0.5
    changefreq = 'weekly'
    protocol = 'https'

    def items(self):
        return []

    def location(self, item):
        return reverse(item)


class FeaturedViewSitemap(Sitemap):
    priority = 0.8
    changefreq = 'daily'
    protocol = 'https'

    def items(self):
        return ['login']

    def location(self, item):
        return reverse(item)


sitemaps = {
    'static': StaticViewSitemap,
    'featured': FeaturedViewSitemap,
}

urlpatterns += [
path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
     name='django.contrib.sitemaps.views.sitemap')
    ]

eventos/urls.py
"""
Propietario: grIT
Contacto: agustin.gomez.mansilla@gmail.com

Use of this code for any commercial purpose is NOT AUTHORIZED.
El uso de éste código para cualquier propósito comercial NO ESTÁ AUTORIZADO.
"""

from django.urls import path
from .views import *

urlpatterns = [
    path('', ListaEventos.as_view()),
    path('e/<slug:evento>', PanelEvento.as_view()),
    path('e/<slug:evento>/frees', PanelFrees.as_view()),
    path('e/<slug:evento>/p/<int:persona>/', PanelEventoPersona.as_view()),
    path('e/<slug:evento>/u/<int:rrpp>/', PanelEventoUsuario.as_view()),
    path('personas', ListaPersona.as_view()),
    path('p/<int:persona>/', PanelPersona.as_view()),
    path('usuarios', ListaUsuarios.as_view()),
    path('u/<int:id_usuario>', PanelUsuario.as_view()),
    path('listas', ListaListasInvitados.as_view()),
    path('l/<slug:lista>/', PanelListasInvitados.as_view()),
    path('importar', ImportView.as_view()),
    path('importar/confirmar/', ImportExcelToEvento.as_view()),
    path('reportes', ReporteView.as_view()),
]

eventos/forms/invitaciones.py
"""
Propietario: grIT
Contacto: agustin.gomez.mansilla@gmail.com

Use of this code for any commercial purpose is NOT AUTHORIZED.
El uso de éste código para cualquier propósito comercial NO ESTÁ AUTORIZADO.
"""
from django import forms
from django.forms.widgets import Widget
from django.db.models import ObjectDoesNotExist

from eventos.models import *
from eventos.forms.validators import *
from eventos.utils import validate_in_group


class DisplayOnlyField(Widget):

    def __init__(self, attrs=None):
        self.attrs = attrs or {}
        self.required = False

    def render(self, name, value, attrs=None, **kwargs):
        try:
            val = value
        except AttributeError:
            val = ""
        return val


class ListaInvitadosForm(forms.ModelForm):

    class Meta:
        model = ListaInvitados
        fields = ['nombre', 'administradores', 'color']

    def __init__(self, *args, **kwargs):
        super(ListaInvitadosForm, self).__init__(*args, **kwargs)
        self.fields["administradores"].queryset = Usuario.objects.filter(is_superuser=False)


class MultiInviAssignToPersona(forms.Form):
    invitaciones = forms.IntegerField(min_value=0, initial=0)
    frees = forms.IntegerField(min_value=0, initial=0)
    lista = forms.ModelChoiceField(queryset=None)

    def __init__(self, usuario, persona, *args, **kwargs):
        evento = kwargs.pop('evento', None)
        super(MultiInviAssignToPersona, self).__init__(*args, **kwargs)
        self.fields['lista'].queryset = ListaInvitados.objects.filter(administradores__in=[usuario])
        try:
            self.fields['lista'].initial = ListaInvitados.objects.get(nombre=usuario.username)
        except ObjectDoesNotExist:
            pass
        if validate_in_group(usuario, ('admin', )):
            max_frees = 1000
        else:
            max_frees = Free.objects.filter(vendedor=usuario, cliente__isnull=True, estado='ACT')
            if evento:
                max_frees = max_frees.filter(evento=evento)
            max_frees = max_frees.count()

        self.fields['frees'].widget.attrs['max'] = max_frees

        for name, field in self.fields.items():
            field.widget.attrs['class'] = 'input'

    def save(self, user, persona, evento, **kwargs):
        n_frees = self.cleaned_data.get('frees')
        n_invis = self.cleaned_data.get('invitaciones')
        if not user in list(self.cleaned_data.get('lista').administradores.all()):
            raise ValidationError("No podes editar esta lista.")
        if evento.estado == 'INA':
            raise ValidationError("El evento esta inactivo!")
        if persona.estado == 'INA':
            raise ValidationError("La persona esta inactiva.")
        if validate_in_group(user, ('admin',)):
            for n in range(n_frees):
                free = Free()
                free.evento = evento
                free.vendedor = user
                free.cliente = persona
                free.estado = 'ACT'
                free.lista = self.cleaned_data['lista']
                free.save()
                free.administrador.set([user])
                free.save()
        else:
            free_set = list(Free.objects.filter(vendedor=user, evento=evento, cliente__isnull=True))
            if n_frees > 0:
                for n in range(n_frees):
                    try:
                        free = free_set[n]
                    except IndexError:
                        self.add_error('frees', 'No tenés suficientes frees! Se añadieron {}'.format(str(n)))
                        break
                    free.cliente = persona
                    free.lista = self.cleaned_data.get('lista')
                    free.estado = 'ACT'
                    free.save()

        if n_invis > 0:
            for n in range(n_invis):
                invi = Invitacion()
                invi.cliente = persona
                invi.vendedor = user
                invi.lista = self.cleaned_data.get('lista')
                invi.evento = evento
                invi.estado = 'ACT'
                invi.save()


class InvitacionAssignForm(MultiInviAssignToPersona):
    persona = forms.CharField(required=True, label="Nombre")
    cedula = forms.CharField(required=True, label="C.I.")
    invitar = forms.BooleanField(widget=forms.HiddenInput, initial=True)

    def __init__(self, user, *args, **kwargs):
        super(InvitacionAssignForm, self).__init__(user, None, *args, **kwargs)
        self.fields['persona'].widget.attrs['class'] = 'input persona'
        self.fields['cedula'].widget.attrs['class'] = 'input cedula'

    def clean(self):
        form_data = super().clean()
        try:
            persona = Persona.objects.get(cedula=form_data['cedula'])
            if persona.nombre != form_data['persona']:
                self.add_error("persona", "Nombre no coincide con una persona existente que tiene la misma C.I.")
                raise ValidationError("Nombre no coincide con una persona existente que tiene la misma C.I.")
        except ObjectDoesNotExist:
            pass

    def clean_cedula(self):
        data = self.cleaned_data['cedula']
        return data.replace('.', '').lstrip(' ').rstrip(' ')

    def save(self, user, evento, **kwargs):
        if evento.estado == 'INA':
            raise ValidationError("El evento está inactivo!")
        nombre = self.cleaned_data['persona']
        cedula = self.cleaned_data['cedula'].replace('.', '')
        persona, created = Persona.objects.get_or_create(nombre=nombre, cedula=cedula)
        if created:
            persona.save()
        super().save(user, persona, evento, **kwargs)


InvitacionAssignFormset = forms.modelformset_factory(Invitacion, form=InvitacionAssignForm, extra=0, exclude=['id'])


class FreeAssign(forms.Form):
    free = forms.IntegerField(min_value=0)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def save(self, user, vendedor, evento):
        if evento.estado == 'INA':
            raise ValidationError("El evento está inactivo!")
        for n in range(self.cleaned_data['free']):
            free = Free()
            free.evento = evento
            free.vendedor = vendedor
            free.cliente = None
            free.estado = 'ACT'
            free.save()
            free.administrador.set([user])
            free.save()


class FreeAssignToUserForm(FreeAssign):
    evento = forms.ModelChoiceField(queryset=Evento.objects.filter(estado='ACT'))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def save(self, user, vendedor):
        evento = self.cleaned_data['evento']
        super().save(user, vendedor, evento)


class ExcelImportForm(forms.Form):
    file = forms.FileField(validators=[file_size], label="Archivo")
    evento = forms.ModelChoiceField(queryset=Evento.objects.filter(estado='ACT'))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['file'].widget.attrs['class'] = 'file-input'


class CheckInForm(forms.Form):
    persona = forms.ModelChoiceField(queryset=Persona.objects.all(), widget=forms.HiddenInput)
    check_invis = forms.IntegerField(initial=0)
    check_frees = forms.IntegerField(initial=0)
    evento = None

    def __init__(self, *args, **kwargs):
        vendedor = kwargs.pop('vendedor', None)
        lista = kwargs.pop('lista', None)
        super().__init__(*args, **kwargs)
        if vendedor:
            self._vendedor = vendedor
        else:
            self._vendedor = None
        if lista:
            self._lista = lista
        else:
            self._lista = None

    def is_valid(self, **kwargs):
        evento = kwargs.pop('evento', None)
        extra = {}
        if self._vendedor:
            extra.update({'vendedor': Usuario.objects.get(pk=self._vendedor)})
        if self._lista:
            extra.update({'lista': ListaInvitados.objects.get(pk=self._lista)})
        if not evento or not isinstance(evento, Evento):
            return False
        self.evento = evento
        r = super().is_valid()
        if r:
            persona = self.cleaned_data['persona']
            n_invis = self.cleaned_data['check_invis']
            n_frees = self.cleaned_data['check_frees']
            print(persona, n_invis, n_frees, evento, extra)
            if n_invis > Invitacion.objects.filter(cliente=persona, evento=evento, estado='ACT', **extra).count() and n_invis > 0:
                self.add_error('check_invis','Demasiados check-ins para esta persona y evento.')
                return False
            elif -n_invis > Invitacion.objects.filter(cliente=persona, evento=evento, estado='USA', **extra).count() and n_invis < 0:
                self.add_error('check_invis', 'Demasiados check-ins para esta persona y evento.')
                return False
            if n_frees > Free.objects.filter(cliente=persona, evento=evento, estado='ACT', **extra).count():
                self.add_error('check_frees', 'Demasiados check-ins para esta persona y evento.')
                return False
            elif -n_frees > Free.objects.filter(cliente=persona, evento=evento, estado='USA', **extra).count() and n_frees < 0:
                self.add_error('check_frees', 'Demasiados check-ins para esta persona y evento.')
                return False
        return r

    def save(self):
        persona = self.cleaned_data['persona']
        evento = self.evento
        n_invis = self.cleaned_data['check_invis']
        n_frees = self.cleaned_data['check_frees']
        extra = {}
        if self._vendedor:
            extra.update({'vendedor': self._vendedor})
        if self._lista:
            extra.update({'lista': self._lista})
        if n_invis>0:
            invis = list(Invitacion.objects.filter(cliente=persona, evento=evento, estado='ACT', **extra))
            for n in range(n_invis):
                invis[n].estado = 'USA'
                invis[n].save()

eventos/views/auth_view.py
"""
/*
Propietario: grIT
Contacto: agustin.gomez.mansilla@gmail.com

Use of this code for any commercial purpose is NOT AUTHORIZED.
El uso de éste código para cualquier propósito comercial NO ESTÁ AUTORIZADO.
*/
"""

from django.views import View
from django.contrib.auth.forms import authenticate, AuthenticationForm
from django.shortcuts import render
from django.contrib.auth import login
from django.http import HttpResponseRedirect
from django.conf import settings

from eventos.models.users import Usuario

import urllib
import os
import json


class LoginView(View):
    template_name = 'register/login.html'
    form_class = AuthenticationForm

    def get_context(self):
        c = dict()
        c['recaptcha_site_key'] = os.getenv('GOOGLE_RECAPTCHA_SITE_KEY')
        c['form'] = self.form_class()
        return c

    def get(self, request, *args, **kwargs):
        c = self.get_context()
        return render(request, self.template_name, c)

    def post(self, request, *args, **kwargs):
        captcha_error = False
        c = self.get_context()
        if settings.DEBUG:
            result = dict(success=True)
        else:
            ''' Begin reCAPTCHA validation '''
            recaptcha_response = request.POST.get('g-recaptcha-response')
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': os.getenv("GOOGLE_RECAPTCHA_SECRET_KEY"),
                'response': recaptcha_response
            }
            data = urllib.parse.urlencode(values).encode()
            req = urllib.request.Request(url, data=data)
            response = urllib.request.urlopen(req)
            result = json.loads(response.read().decode())
            ''' End reCAPTCHA validation '''
        if result['success']:
            username = request.POST['username']
            password = request.POST['password']

            user = authenticate(
                request=request,
                username=username,
                password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    try:
                        return HttpResponseRedirect(request.GET['next'])
                    except:
                        return HttpResponseRedirect('/')
                else:
                    c['alert_msg'] = ['Usuario desactivado. Contacta con tu administrador.']
            else:
                form = self.form_class(request=request)
                c['form_error'] = form.get_invalid_login_error()
        else:
            captcha_error = True
        c['recaptcha_error'] = captcha_error
        return render(request, self.template_name, c)

eventos/views/basic_view.py
"""
/*
Propietario: grIT
Contacto: agustin.gomez.mansilla@gmail.com

Use of this code for any commercial purpose is NOT AUTHORIZED.
El uso de éste código para cualquier propósito comercial NO ESTÁ AUTORIZADO.
*/
"""
from django.views import View
from eventos.models import Evento
from django.shortcuts import render
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import HttpResponseRedirect


class BasicView(UserPassesTestMixin, View):
    template_name = None

    def test_func(self):
        return self.request.user.is_authenticated

    def handle_no_permission(self):
        return HttpResponseRedirect('/accounts/login')

    def get_context_data(self, user, *args, **kwargs):
        c = dict()
        c['usuario'] = user
        c['groups'] = [g.name for g in user.groups.all()]
        c['nav_eventos'] = Evento.objects.filter(estado='ACT').order_by('-fecha')
        c['back'] = '/'
        c['alert_msg'] = self.request.session.pop('alert_msg', [])
        return c

    def get(self, request, c):
        return render(request, self.template_name, context=c)


class AdminView(BasicView):

    def handle_no_permission(self):
        return HttpResponseRedirect('/')

    def test_func(self):
        return self.request.user.groups.filter(name='admin').exists()


class SuperAdminView(BasicView):
    def handle_no_permission(self):
        return HttpResponseRedirect('/')

    def test_func(self):
        return self.request.user.is_superuser

eventos/views/errors.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView

def csrf_fail(request, reason=""):
    c = dict(reason=reason)
    return render(request, 'errors/csrf_fail.html', c, status=403)

eventos/templates/eventos/lista_eventos.html
{% extends 'base.html' %}
{% load auth_extras %}
{% load static %}

{% block breadcrumbs %}
    <li class="is-active"><a href="#">Eventos</a></li>
{% endblock %}

{% block content %}

<script src="{% static 'js/sort.js' %}"></script>
<h1 class="title is-1"> Eventos </h1>
{% include 'eventos/tablas/tabla_eventos.html' %}

{% if form %}

{% endif %}
{% endblock %}

{% block dialog %}
{% if request.user|has_group:"admin" %}
<div class="button-container">
    <button id="add-form" class="plus-button green"><i class="fa fa-plus-circle"></i></button>
</div>
<div class="modal" id="form-dialog">
      <div class="modal-content is-fullheight">
          <span id='form-close' class="close">&times;</span>
            <form class="modal-form" action="" method="post">
                {% csrf_token %}
                {% include 'eventos/forms/evento-form.html' %}
                <div class="control">
                <input type="submit" class="button is-info" value="Crear Evento">
                </div>
            </form>
      </div>
</div>
{% include 'eventos/setups/modal_setup.html' with ModalName='form'%}
<div class="modal" id="edit-dialog">
      <div class="modal-content is-fullheight">
          <span id='edit-close' class="close">&times;</span>
            <form class="modal-form" id="edit-form" action="" method="post">
                {% csrf_token %}
                {% include 'eventos/forms/evento-form.html' with form=edit_form %}
                <div class="control">
                    <input type="submit" class="button is-info" value="Editar Evento">
                </div>
                <input type="hidden" name="edit" id="id_evento" value="">
            </form>
                <button class="button is-danger" id="delete_evento_btn">
                    Borrar Evento
                </button>

      </div>
</div>
{% include 'eventos/setups/modal_setup.html' with ModalName='edit' noBtn=1%}
<script nonce="{{request.csp_nonce}}">
    function openEditModal(id, name, fecha){
        checkinModal = document.getElementById("edit-dialog");
        checkinModal.classList.add("is-active");
        document.getElementById("{{edit_form.name.id_for_label}}").value=name;
        document.getElementById("{{edit_form.fecha.id_for_label}}").value=fecha;
        document.getElementById("id_evento").value=id;
        document.getElementById("delete_evento_btn").remove();
        btn = document.createElement("button");
        btn.classList.add("button");
        btn.classList.add("is-danger");
        btn.innerHTML = "Borrar Evento";
        btn.id = "delete_evento_btn";
        btn.addEventListener("click", function () {
            openDeleteModal(id, name);
        });
        document.getElementById("edit-form").after(btn);
    };
</script>
<div class="modal" id="delete-dialog">
      <div class="modal-content is-fullheight">
          <span id='delete-close' class="close">&times;</span>
          <p class="modal-title"><b>Atención!</b></p>
          <p class="modal-text">Al borrar el evento se perderá <b>toda</b> la información de invitaciones y frees asociadas. </p>
          <p class="modal-text">Escribí <b>"<span id="delete_evento_help"></span>"</b> y apretá el botón si estás seguro de querer borrarlo:</span></p>
            <form class="modal-form" action="" method="post">
                {% csrf_token %}
                {% include 'eventos/forms/evento-form.html' with form=delete_form %}
                <div class="control">
                    <input type="submit" class="button is-danger" value="Borrar Evento">
                </div>
                <input type="hidden" name="delete_evento" id="delete_evento" value="">
            </form>
      </div>
</div>
<script nonce="{{request.csp_nonce}}">
    function openDeleteModal(id, name){
        deleteModal = document.getElementById("delete-dialog");
        deleteModal.classList.add("is-active");
        document.getElementById("delete_evento").value=id;
        document.getElementById("delete_evento_help").innerHTML=name;
    };
</script>
{% include 'eventos/setups/modal_setup.html' with ModalName='delete' noBtn=1%}
{% endif %}
{% endblock %}

eventos/templates/eventos/persona_view_evento.html
{% extends 'base.html' %}
{% load static %}
{% load auth_extras %}
{% block go_back %} / {% endblock %}
{% block content %}
<h1 class="title is-1">
    {{evento.name}}
</h1>
<div class="card persona-card">
    <header class="card-header">
        <h2 class="title is-2">
            {{persona.nombre}}
        </h2>
    </header>
    <div class="card-content">
        <div class="media">
<!--            <div class="media-left">-->
<!--                <figure class="image is-150x150">-->
<!--                    <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">-->
<!--                </figure>-->
<!--            </div>-->
            <div class="media-content">
                <h3 class="subtitle is-3">
                    C.I.: {{persona.cedula}}
                </h3>
            </div>
        </div>
    </div>
</div>
<h2 class="title">
    Invitaciones:
</h2>
{% include 'eventos/tablas/tabla-invitaciones.html' %}

{% endblock %}

{% block dialog %}

{% if request.user|has_group:"admin" or request.user|has_group:"rrpp" %}
<div class="button-container">
    <button id="add-form" class="plus-button green"><i class="fa fa-plus-circle"></i></button>
</div>
<div class="modal" id="form-dialog">
    <div class="modal-content is-fullheight">
        <span id='form-close' class="close">&times;</span>
        <form class="modal-form" id="invi-form" action="" method="post">
            {% csrf_token %}
            {% include 'eventos/forms/multiassign-form.html' with form=form %}
        </form>
    </div>
</div>
{% include 'eventos/setups/modal_setup.html' with ModalName='form'%}
<script nonce="{{request.csp_nonce}}">
    document.addEventListener('DOMContentLoaded', function() {
        form = document.getElementById('invi-form');
        inputs = form.querySelectorAll('input');
        inputs.forEach((input) => {
            input.addEventListener('input', () => {
                checkForm();
            })
        });
        function checkForm() {
            let form = document.getElementById('invi-form');
            let buttonSend = form.getElementsByClassName('is-info')[0]
            let frees = Number(document.getElementById('id_frees').value);
            let invis = Number(document.getElementById('id_invitaciones').value);
            if (frees+invis>0) {
              buttonSend.disabled = false;
            } else {
              buttonSend.disabled = true;
            }
        }
    });
</script>
{% endif %}

{% if request.user|has_group:"admin" or request.user|has_group:"entrada" %}
<div class="modal" id="checkin-dialog">
      <div class="modal-content">
          <span id='checkin-close' class="close">&times;</span>
          <form class="modal-form" id="checkin-form" method="post" action="">
            {% csrf_token %}
            {% include 'eventos/forms/checkin-form.html' with form=checkin_form %}
              <input id="id_checkin" name="checkin" value="" type="hidden">
              <input id="id_lista" name="lista" value="" type="hidden">
          </form>
      </div>
</div>

<script nonce="{{request.csp_nonce}}">
    document.addEventListener('DOMContentLoaded', function() {
        var form = document.getElementById('checkin-form');
        var inputs = form.querySelectorAll('input');
        inputs.forEach((input) => {
            input.addEventListener('input', (event) => {
                checkCheckInForm(event.target);
            })
        });
        function checkCheckInForm(t) {
                let form = document.getElementById('checkin-form');
                let inputs = form.querySelectorAll('input');
                let buttonSend = form.getElementsByClassName('is-info')[0];
                let frees = Number(document.getElementById('id_check_frees').value);
                let invis = Number(document.getElementById('id_check_invis').value);
                if (frees!=0 || invis !=0) {
                  buttonSend.disabled = false;
                } else {
                  buttonSend.disabled = true;
                }
        };
    });

    function openCheckInModal(id, f_max, f_min, i_max, i_min, lista) {
        checkinModal = document.getElementById("checkin-dialog");
        checkinModal.classList.add("is-active");
        document.getElementById("{{checkin_form.persona.id_for_label}}").value={{persona.pk}};
        document.getElementById("{{checkin_form.check_frees.id_for_label}}").max=f_max-f_min;
        document.getElementById("{{checkin_form.check_frees.id_for_label}}").min=-f_min;
        document.getElementById("{{checkin_form.check_frees.id_for_label}}").value=0;
        document.getElementById("{{checkin_form.check_invis.id_for_label}}").max=i_max-i_min;
        document.getElementById("{{checkin_form.check_invis.id_for_label}}").min=-i_min;
        document.getElementById("{{checkin_form.check_invis.id_for_label}}").value=0;
        document.getElementById("id_checkin").value=id;
        document.getElementById("id_lista").value=lista;
    };

</script>
{% include 'eventos/setups/modal_setup.html' with ModalName='checkin' noBtn=1%}
{% endif %}
{% endblock %}

eventos/templates/eventos/rrpp_view_evento.html
{% extends 'base.html' %}
{% load static %}
{% load auth_extras %}
{% block content %}
<h1 class="title is-1">
    {{evento.name}}
</h1>
<div class="card persona-card">
    <header class="card-header">
        <h2 class="title is-2">
            {{rrpp.username}}
        </h2>
    </header>
    <div class="card-content">
        <div class="media">
        </div>
        {{rrpp.first_name}}
    </div>
</div>
<h2 class="title">
    Invitaciones:
</h2>
{% include 'eventos/tablas/tabla-invitaciones.html' %}

{% endblock %}

{% block dialog %}
{% if request.user|has_group:"admin" or request.user|has_group:"entrada" %}
<div class="modal" id="checkin-dialog">
      <div class="modal-content">
          <span id='checkin-close' class="close">&times;</span>
          <form class="modal-form" id="checkin-form" method="post" action="">
            {% csrf_token %}
            {% include 'eventos/forms/checkin-form.html' with form=checkin_form %}
              <input id="id_checkin" name="checkin" value="" type="hidden">
              <input id="id_lista" name="lista" value="" type="hidden">
          </form>
      </div>
</div>
<script nonce="{{request.csp_nonce}}">

    var form = document.getElementById('checkin-form');
    var inputs = form.querySelectorAll('input');
    inputs.forEach((input) => {
        input.addEventListener('input', (event) => {
            checkCheckInForm(event.target);
        })
    });
    function checkCheckInForm(t) {
            let form = document.getElementById('checkin-form');
            let inputs = form.querySelectorAll('input');
            let buttonSend = form.getElementsByClassName('is-info')[0];
            let frees = Number(document.getElementById('id_check_frees').value);
            let invis = Number(document.getElementById('id_check_invis').value);
            if (frees!=0 || invis !=0) {
              buttonSend.disabled = false;
            } else {
              buttonSend.disabled = true;
            }
    };
</script>
<script nonce="{{request.csp_nonce}}">
    function openCheckInModal(id, f_max, f_min, i_max, i_min, lista){
        checkinModal = document.getElementById("checkin-dialog");
        checkinModal.classList.add("is-active");
        document.getElementById("{{checkin_form.persona.id_for_label}}").value=id;
        document.getElementById("{{checkin_form.check_frees.id_for_label}}").max=f_max-f_min;
        document.getElementById("{{checkin_form.check_frees.id_for_label}}").min=-f_min;
        document.getElementById("{{checkin_form.check_frees.id_for_label}}").value=0;
        document.getElementById("{{checkin_form.check_invis.id_for_label}}").max=i_max-i_min;
        document.getElementById("{{checkin_form.check_invis.id_for_label}}").min=-i_min;
        document.getElementById("{{checkin_form.check_invis.id_for_label}}").value=0;
        document.getElementById("id_checkin").value={{rrpp.pk}};
        document.getElementById("id_lista").value=lista;
    };

</script>
{% include 'eventos/setups/modal_setup.html' with ModalName='checkin' noBtn=1%}
{% endif %}
{% endblock %}